[add] eslint
idea2app/React-MobX-Bootstrap-ts pull request #16
Opened 2024-09-09 11:51 UTC by Soecka

[add] eslint, lint-staged
[update] dependencies

2024-09-09 18:33 UTC, TechQuery requested changes

2024-09-09 18:33 UTC, TechQuery commented on package.json
> +        ]
先格式化再检查代码规范会比较好

2024-09-09 18:33 UTC, TechQuery commented on package.json
> +        "@types/node": "^20.16.2",
其它依赖 Node.js 20 的 GitHub actions 也都升级一下，参见：idea2app/Next-Bootstrap-ts#45

2024-09-09 18:33 UTC, TechQuery commented on eslint.config.mjs
> +    // typescript
```suggestion
    // TypeScript
```

2024-09-09 18:33 UTC, TechQuery commented on eslint.config.mjs
> +    // js
```suggestion
    // JavaScript
```

2024-09-09 18:33 UTC, TechQuery commented on eslint.config.mjs
> +    // react
```suggestion
    // React
```

2024-09-09 18:33 UTC, TechQuery commented on eslint.config.mjs
> +    // markdown
```suggestion
    // MarkDown
```

2024-09-09 18:33 UTC, TechQuery commented on package.json
> +        "*.{html,md,less,json,yml,js,ts,tsx}": [
```suggestion
        "*.{html,md,less,json,yml,js,mjs,ts,tsx}": [
```
`tsconfig.json` 里也开一下 `checkJs`，并 
`include` `*.mjs`。

2024-09-10 05:04 UTC, Soecka commented on package.json
> +        ]
格式不对会影响 eslint 规则通过？

2024-09-10 05:24 UTC, Soecka commented on package.json
> +        "@types/node": "^20.16.2",
两者没有类似的 action 镜像，这个仓库只有一个 `pull-request.yml`

2024-09-10 06:28 UTC, TechQuery commented on package.json
> +        "@types/node": "^20.16.2",
> 两者没有类似的 action 镜像，这个仓库只有一个 `pull-request.yml`

4 处步骤一样且可升级：
https://github.com/idea2app/React-MobX-Bootstrap-ts/blob/dfc2a854ba245c1b056a07a5c38468585060c3f1/.github/workflows/main.yml#L14-L33

2024-09-10 06:29 UTC, TechQuery commented on package.json
> +        ]
> 格式不对会影响 eslint 规则通过？

有少数规则会，因为代码越格式规范出问题的概率越小。

2024-09-10 06:31 UTC, TechQuery requested changes

2024-09-10 06:31 UTC, TechQuery commented on package.json
> +        "koajax": "^3.0.0",
为啥降了两个小版本？

2024-09-10 06:39 UTC, TechQuery requested changes

2024-09-10 06:39 UTC, TechQuery commented on package.json
>          "mobx-restful-table": "^2.0.0-rc.1",
还有版本可以升，用 Version lens 插件统一清查一下。

2024-09-10 07:26 UTC, Soecka commented on package.json
> +        ]
我是根据官方文档推荐写的
https://github.com/lint-staged/lint-staged#task-concurrency

2024-09-10 07:32 UTC, Soecka commented on package.json
> +        "koajax": "^3.0.0",
之前 3.0.2 安装不了，不知道是不是 npm 临时炸了

2024-09-10 07:53 UTC, TechQuery requested changes

2024-09-10 07:53 UTC, TechQuery commented on .github/workflows/main.yml
> +              if: ${{ env.VERCEL_TOKEN && env.VERCEL_ORG_ID && env.VERCEL_PROJECT_ID }}
我说的是让你参考其它模板仓库来把每一个步骤引用的 action 版本升上去，不是让你删减一大堆步骤……

2024-09-10 07:58 UTC, Soecka commented on package.json
> +        ]
按照步骤，只要 `eslint --fix` 出问题都会再过一遍，用 prettier 收尾是正常流程？

2024-09-10 08:33 UTC, TechQuery requested changes

2024-09-10 08:33 UTC, TechQuery commented on .github/workflows/main.yml
> +        runs-on: ubuntu-latest
```suggestion
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
```

2024-09-10 08:33 UTC, TechQuery commented on .github/workflows/pull-request.yml
> +        runs-on: ubuntu-latest
```suggestion
        runs-on: ubuntu-latest
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
```

2024-09-10 08:34 UTC, TechQuery approved these changes

2024-09-12 20:40 UTC, TechQuery requested changes

2024-09-12 20:40 UTC, TechQuery commented on eslint.config.mjs
> +            ['@typescript-eslint']: tsEslint.plugin,
```suggestion
            '@typescript-eslint': tsEslint.plugin,
```
下同

2024-09-12 20:40 UTC, TechQuery commented on eslint.config.mjs
> +            },
Node.js 呢？

2024-09-13 15:17 UTC, TechQuery requested changes

2024-09-13 15:17 UTC, TechQuery commented on package.json
> +        "react-dom": "18.3.1",
```suggestion
        "react": "^18.3.1",
        "react-dom": "^18.3.1",
```
前端库一般不需要锁版本，你需要重新执行一下安装命令更新锁文件。

2024-09-13 15:17 UTC, TechQuery commented on package.json
> +        "@types/react-dom": "18.3.0",
```suggestion
        "@types/react": "^18.3.5",
        "@types/react-dom": "^18.3.0",
```

2024-09-13 15:17 UTC, TechQuery commented on package.json
> +        "eslint": "9.10.0",
```suggestion
        "eslint": "^9.10.0",
```

2024-09-13 15:17 UTC, TechQuery commented on src/index.tsx
> +root.render(<PageFrame />);
```suggestion
createRoot(document.querySelector('#app')).render(<PageFrame />);
```

2024-09-14 06:32 UTC, TechQuery requested changes

2024-09-14 06:32 UTC, TechQuery commented on ReadMe.md
> +-   Component engine: [React v18][9]
```suggestion
-   Component engine: [React v18][1]
```
直接复用现有链接即可

2024-09-14 06:32 UTC, TechQuery commented on ReadMe.md
> +[9]: https://react.dev/
```suggestion
```

2024-09-14 06:33 UTC, TechQuery approved these changes

2024-09-14 06:36 UTC, merged